services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_strong_password123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
  api:
    build: .
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=CRNProductDb;User Id=sa;Password=Your_strong_password123!;TrustServerCertificate=True"
      Jwt__Key: "CRN-Assessment-Development-Key-Change-In-Production-At-Least-32-Chars!"
    ports:
      - "8080:8080"
volumes:
  sql_data:
