using System.IdentityModel.Tokens.Jwt; using System.Security.Claims; using System.Security.Cryptography; using System.Text; using CRN.ProductApi.Application.DTOs; using CRN.ProductApi.Application.Interfaces; using CRN.ProductApi.Domain.Entities; using CRN.ProductApi.Infrastructure.Data; using Microsoft.EntityFrameworkCore; using Microsoft.Extensions.Configuration; using Microsoft.IdentityModel.Tokens;
namespace CRN.ProductApi.Infrastructure.Identity;
public class JwtService(IConfiguration config,ApplicationDbContext db) : IJwtService
{
 public (string Token,DateTime ExpiresOnUtc) CreateAccessToken(UserAccount user){var s=config.GetSection("Jwt");var key=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(s["Key"]!));var minutesStr=s["AccessTokenExpirationMinutes"]??s["AccessTokenMinutes"]??"15";var exp=DateTime.UtcNow.AddMinutes(int.Parse(minutesStr));var claims=new[]{new Claim(JwtRegisteredClaimNames.Sub,user.Username),new Claim(ClaimTypes.Name,user.Username),new Claim(ClaimTypes.Role,user.Role),new Claim(JwtRegisteredClaimNames.Jti,Guid.NewGuid().ToString())};var token=new JwtSecurityToken(s["Issuer"],s["Audience"],claims,expires:exp,signingCredentials:new SigningCredentials(key,SecurityAlgorithms.HmacSha256));return(new JwtSecurityTokenHandler().WriteToken(token),exp);}
 public async Task<AuthResponse> CreateAndPersistTokensAsync(UserAccount user,CancellationToken ct){var access=CreateAccessToken(user);var raw=Convert.ToBase64String(RandomNumberGenerator.GetBytes(64));var daysStr=config["Jwt:RefreshTokenExpirationDays"]??config["Jwt:RefreshTokenDays"]??"7";var entity=new RefreshToken{UserAccountId=user.Id,TokenHash=Hash(raw),CreatedOnUtc=DateTime.UtcNow,ExpiresOnUtc=DateTime.UtcNow.AddDays(int.Parse(daysStr))};db.RefreshTokens.Add(entity);await db.SaveChangesAsync(ct);return new AuthResponse(access.Token,raw,access.ExpiresOnUtc,entity.ExpiresOnUtc);}
 public async Task<AuthResponse> RefreshAsync(string accessToken,string refreshToken,CancellationToken ct){var principal=GetPrincipalIgnoringExpiry(accessToken);var username=principal?.FindFirstValue(ClaimTypes.Name)??principal?.FindFirstValue(JwtRegisteredClaimNames.Sub);if(username is null)throw new SecurityTokenException("Invalid access token.");var user=await db.Users.Include(x=>x.RefreshTokens).SingleOrDefaultAsync(x=>x.Username==username,ct)??throw new SecurityTokenException("User not found.");var token=user.RefreshTokens.FirstOrDefault(x=>x.TokenHash==Hash(refreshToken)&&x.IsActive)??throw new SecurityTokenException("Invalid or expired refresh token.");token.RevokedOnUtc=DateTime.UtcNow;await db.SaveChangesAsync(ct);return await CreateAndPersistTokensAsync(user,ct);}
 private ClaimsPrincipal? GetPrincipalIgnoringExpiry(string token){try{var s=config.GetSection("Jwt");var p=new JwtSecurityTokenHandler();return p.ValidateToken(token,new TokenValidationParameters{ValidateIssuer=true,ValidIssuer=s["Issuer"],ValidateAudience=true,ValidAudience=s["Audience"],ValidateIssuerSigningKey=true,IssuerSigningKey=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(s["Key"]!)),ValidateLifetime=false,ClockSkew=TimeSpan.Zero},out _);}catch{return null;}}
 private static string Hash(string value){using var sha=SHA256.Create();return Convert.ToHexString(sha.ComputeHash(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();}
}
