using System.Text.Json.Serialization; using Asp.Versioning; using CRN.ProductApi.Extensions; using CRN.ProductApi.Infrastructure.Data; using CRN.ProductApi.Infrastructure.Identity; using CRN.ProductApi.Middleware; using Microsoft.EntityFrameworkCore; using Microsoft.OpenApi.Models;
var builder=WebApplication.CreateBuilder(args);
builder.Logging.AddConsole();
builder.Services.AddControllers().AddJsonOptions(o=>o.JsonSerializerOptions.ReferenceHandler=ReferenceHandler.IgnoreCycles);
builder.Services.AddEndpointsApiExplorer();builder.Services.AddSwaggerGen(o=>{o.SwaggerDoc("v1",new OpenApiInfo{Title="CRN Product API",Version="v1",Description="RESTful Product CRUD API technical assessment"});o.AddSecurityDefinition("Bearer",new OpenApiSecurityScheme{Type=SecuritySchemeType.Http,Scheme="bearer",BearerFormat="JWT",Name="Authorization",In=ParameterLocation.Header});o.AddSecurityRequirement(new OpenApiSecurityRequirement{{new OpenApiSecurityScheme{Reference=new OpenApiReference{Type=ReferenceType.SecurityScheme,Id="Bearer"}},Array.Empty<string>()}});});
builder.Services.AddProjectServices(builder.Configuration);builder.Services.AddCors(o=>o.AddPolicy("Default",p=>p.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));builder.Services.AddResponseCompression();builder.Services.AddApiVersioning(o=>{o.DefaultApiVersion=new ApiVersion(1,0);o.AssumeDefaultVersionWhenUnspecified=true;o.ReportApiVersions=true;});
var app=builder.Build();
using(var scope=app.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();await db.Database.EnsureCreatedAsync();if(!await db.Users.AnyAsync()){db.Users.Add(new CRN.ProductApi.Domain.Entities.UserAccount{Username="admin",PasswordHash=PasswordService.Hash("Admin@123"),Role="Admin"});db.Users.Add(new CRN.ProductApi.Domain.Entities.UserAccount{Username="user",PasswordHash=PasswordService.Hash("User@123"),Role="User"});await db.SaveChangesAsync();}}
app.UseMiddleware<ExceptionHandlingMiddleware>();app.Use(async(ctx,nxt)=>{ctx.Response.Headers.Append("X-Content-Type-Options","nosniff");ctx.Response.Headers.Append("X-Frame-Options","DENY");ctx.Response.Headers.Append("X-XSS-Protection","1; mode=block");ctx.Response.Headers.Append("Referrer-Policy","strict-origin-when-cross-origin");await nxt();});app.UseResponseCompression();app.UseSwagger();app.UseSwaggerUI();app.UseHttpsRedirection();app.UseCors("Default");app.UseAuthentication();app.UseAuthorization();app.MapControllers();app.Run();public partial class Program{}
